### ISSUE TITLE
amour stnads for furrys idea

### ISSUE THREAD

**Issue by goldrichman9Modded** [gengyoubo/changed-plus#12]
for the latex centaur & mermaid amour stand, amour stands for legless and multilegged latex beast

**Comment by gengyoubo** [comment]
What’s amour stand?

**Comment by goldrichman9Modded** [comment]
> What’s amour stand?

like a amour stand for the [Latex Centaur] muti leg amour stand and [Latex Siren] for the bottom half of the amour stand

**Comment by goldrichman9Modded** [comment]
> What’s amour stand?
This
![IMG_1637](https://github.com/gengyoubo/changed-plus/assets/168244776/8e40c919-a218-4596-a7ce-fd7ddb7aa820)

**Comment by gengyoubo** [comment]
It might be hard to implement right now, maybe if I have a good knowledge of java.
