### ISSUE TITLE
Idea for the mod

### ISSUE THREAD

**Issue by goldrichman9Modded** [gengyoubo/changed-plus#9]
Maybe add a latex crystal sword made from the dark latex shards or green shards and can maybe be made into amour and for humans maybe a crow bar that can be made out of iron also if you're holding a sword you can imbue it with latex with the beast you are. Ex. Imbuing a diamond sword with black latex as a dark latex

**Comment by gengyoubo** [comment]
https://github.com/gengyoubo/changed_plus_industry/issues/2
